<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \BKozlic\MultipleWishlist\ViewModel\MultipleWishlist $viewModel
 */

$viewModel = $block->getViewModel();
$inputValues = $viewModel->getManageFormInputValues();
?>
<form action="<?= $block->escapeUrl($viewModel->getFormPostUrl()); ?>" method="post" data-mage-init='{"validation":{}}'>
    <?= $block->getBlockHtml('formkey') ?>
    <input type="hidden" name="id" value="<?= $block->escapeHtml($inputValues['id'] ?? ''); ?>">
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Wishlist Information')); ?></span></legend>
        <div class="field wishlist-name required">
            <label class="label" for="wishlist">
                <span><?= $block->escapeHtml(__('Wishlist Name')); ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="name"
                       value="<?= $block->escapeHtml($inputValues['name'] ?? ''); ?>"
                       title="<?= $block->escapeHtmlAttr(__('Wishlist Name')); ?>"
                       class="required-entry"
                       id="wishlist">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action save primary"
                    title="<?= $block->escapeHtmlAttr(__('Save Wishlist')); ?>">
                <span><?= $block->escapeHtml(__('Save Wishlist')); ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action" href="<?= $block->escapeUrl($block->getUrl('*/*')); ?>">
                <span><?= $block->escapeHtml(__('Go back')); ?></span>
            </a>
        </div>
    </div>
</form>
