<?php
/**
 * @category  BKozlic
 * @package   BKozlic\MultipleWishlist
 * @author    Berin Kozlic - berin.kozlic@gmail.com
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @var \BKozlic\MultipleWishlist\Block\MultipleWishlistSwitcher $block
 */

$collection = $block->getCollection();
?>
<?php if ($block->isWishlistAllowed() && $block->isMultipleWishlistAllowed()): ?>
    <div class="multiple-wishlist-manager">
        <div class="toolbar wishlist-switcher">
            <?php if (count($collection)): ?>
                <label for="wishlist-select-switcher" class="wishlist-switcher-label">
                    <?= $block->escapeHtml(__('Wishlist')); ?>
                </label>
                <select id="wishlist-select-switcher" data-mage-init='{"redirectUrl": {"event":"change"}}' class="limiter-options">
                    <?php if ($block->defaultWishlistHasItems()): ?>
                        <option value="<?= $block->escapeHtmlAttr($block->getMultipleWishlistUrl(null)) ?>"
                            <?php if ($block->isSelectedWishlist(null)): ?>
                                selected
                            <?php endif; ?>>
                            <?= $block->escapeHtml(__('Default Wishlist')); ?>
                        </option>
                    <?php endif; ?>

                    <?php foreach ($collection as $multipleWishlist): ?>
                        <option value="<?= $block->escapeHtmlAttr($block->getMultipleWishlistUrl($multipleWishlist->getId())); ?>"
                            <?php if ($block->isSelectedWishlist($multipleWishlist->getId())): ?>
                                selected
                            <?php endif; ?>>
                            <?= $block->escapeHtml($multipleWishlist->getName()); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            <?php endif; ?>

            <a class="action primary"
               href="<?= $block->escapeUrl($block->getUrl('multiplewishlist/manage/index')); ?>">
                <span><?= $block->escapeHtml(__('Manage Wishlists')); ?></span>
            </a>
        </div>
    </div>
<?php endif; ?>
