<?php
/**
 * @category  BKozlic
 * @package   BKozlic\MultipleWishlist
 * @author    Berin Kozlic - berin.kozlic@gmail.com
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/* @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column $block */
?>

<a href="#" title="<?= $block->escapeHtmlAttr(__('Move')) ?>" data-role="move"
   data-item="<?= $block->escapeHtmlAttr($block->getItem()->getId()); ?>" class="btn-move action move">
    <span><?= $block->escapeHtml(__('Move')) ?></span>
</a>
