<?php
/**
 * @category  BKozlic
 * @package   BKozlic\MultipleWishlist
 * @author    Berin Kozlic - berin.kozlic@gmail.com
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Button $block */
?>
<?php if ($block->getWishlist()->getItemsCount() && $block->getWishlist()->isSalable()): ?>
    <button type="button" data-role="move" title="<?= $block->escapeHtmlAttr(__('Move Items')); ?>" class="action move-items">
        <span><?= $block->escapeHtml(__('Move Items')) ?></span>
    </button>
<?php endif; ?>
