<?php
/**
 * @category  BKozlic
 * @package   BKozlic\MultipleWishlist
 * @author    Berin Kozlic - berin.kozlic@gmail.com
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \BKozlic\MultipleWishlist\ViewModel\MultipleWishlist $viewModel
 */
$viewModel = $block->getViewModel();
//@TODO Provide options to widget here
$block->getUrl()
?>
<?php if ($viewModel->isCustomerLoggedIn() && $viewModel->canShowModal()): ?>
    <div class="multiplewishlist-modal" data-mage-init='{"multipleWishlistModal": {}}'
         data-bind="scope: 'multiple_wishlists'" data-item="multiple_wishlists">
        <form id="multiple-wishlist-form" action="#" method="post">
            <!-- ko ifnot: hasWishlists() -->
                <?= __('You don\'t have created wishlists. Item will be assigned to the Default wishlist.'); ?>
            <!-- /ko -->

            <!-- ko template: getTemplate() --><!-- /ko -->
        </form>
    </div>

    <script type="text/x-magento-init">
        {
            "[data-item='multiple_wishlists']": {
                "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout(); ?>
            }
        }
    </script>
<?php endif; ?>
