<?php
/**
 * @category  BKozlic
 * @package   BKozlic\MultipleWishlist
 * @author    Berin Kozlic - berin.kozlic@gmail.com
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \BKozlic\MultipleWishlist\ViewModel\MultipleWishlist $viewModel
 */
$viewModel = $block->getViewModel();
?>
<?php if ($viewModel->isCustomerLoggedIn()): ?>
    <div class="multiplewishlist-modal" data-mage-init='{"multipleWishlistModal": {}}'>
        Modal
    </div>
<?php endif; ?>
